// actions for authentication
export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";

export const AUTH_LOGOUT = "AUTH_LOGOUT";

// actions for users
export const FETCH_USERS_START = "FETCH_USERS_START";
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_USERS_FAIL = "FETCH_USERS_FAIL";

export const FETCH_USER_BY_ID_START = "FETCH_USER_BY_ID_START";
export const FETCH_USER_BY_ID_SUCCESS = "FETCH_USER_BY_ID_SUCCESS";
export const FETCH_USER_BY_ID_FAIL = "FETCH_USER_BY_ID_FAIL";

export const ADD_USER_START = "ADD_USER_START";
export const ADD_USER_SUCCESS = "ADD_USER_SUCCESS";
export const ADD_USER_FAIL = "ADD_USER_FAIL";

export const EDIT_USER = "EDIT_USER";

export const DELETE_USER_BY_ID_START = "DELETE_USER_BY_ID_START";
export const DELETE_USER_BY_ID_SUCCESS = "DELETE_USER_BY_ID_SUCCESS";
export const DELETE_USER_BY_ID_FAIL = "DELETE_USER_BY_ID_FAIL";

export const ON_CHANGE_USERFORM = "ON_CHANGE_USERFORM";

// actions for tanks
export const FETCH_TANKS_START = "FETCH_TANKS_START";
export const FETCH_TANKS_SUCCESS = "FETCH_TANKS_SUCCESS";
export const FETCH_TANKS_FAIL = "FETCH_TANKS_FAIL";

export const FETCH_TANKS_OVERVIEW_START = "FETCH_TANKS_OVERVIEW_START";
export const FETCH_TANKS_OVERVIEW_SUCCESS = "FETCH_TANKS_OVERVIEW_SUCCESS";
export const FETCH_TANKS_OVERVIEW_FAIL = "FETCH_TANKS_OVERVIEW_FAIL";

export const ADD_TANK_START = "ADD_TANK_START";
export const ADD_TANK_SUCCESS = "ADD_TANK_SUCCESS";
export const ADD_TANK_FAIL = "ADD_TANK_FAIL";

export const FETCH_TANK_BY_ID_START = "FETCH_TANK_BY_ID_START";
export const FETCH_TANK_BY_ID_SUCCESS = "FETCH_TANK_BY_ID_SUCCESS";
export const FETCH_TANK_BY_ID_FAIL = "FETCH_TANK_BY_ID_FAIL";

// export const ON_CHANGE_TANKFORM = "ON_CHANGE_TANKFORM";

export const FETCH_TANK_OVERVIEW_BY_ID_START = "FETCH_TANK_OVERVIEW_BY_ID_START";
export const FETCH_TANK_OVERVIEW_BY_ID_SUCCESS = "FETCH_TANK_OVERVIEW_BY_ID_SUCCESS";
export const FETCH_TANK_OVERVIEW_BY_ID_FAIL = "FETCH_TANK_OVERVIEW_BY_ID_FAIL";

export const FETCH_TANK_SENSORLOG_BY_ID_START = "FETCH_TANK_SENSORLOG_BY_ID_START";
export const FETCH_TANK_SENSORLOG_BY_ID_SUCCESS = "FETCH_TANK_SENSORLOG_BY_ID_SUCCESS";
export const FETCH_TANK_SENSORLOG_BY_ID_FAIL = "FETCH_TANK_SENSORLOG_BY_ID_FAIL";

export const DELETE_TANK_BY_ID_START = "DELETE_TANK_BY_ID_START";
export const DELETE_TANK_BY_ID_SUCCESS = "DELETE_TANK_BY_ID_SUCCESS";
export const DELETE_TANK_BY_ID_FAIL = "DELETE_TANK_BY_ID_FAIL";

export const POST_SLOTSTATUS_TANK_START = "POST_SLOTSTATUS_TANK_START";
export const POST_SLOTSTATUS_TANK_SUCCESS = "POST_SLOTSTATUS_TANK_SUCCESS";
export const POST_SLOTSTATUS_TANK_FAIL = "POST_SLOTSTATUS_BY_ID_FAIL";

// actions for companies
export const FETCH_COMPANIES_START = "FETCH_COMPANIES_START";
export const FETCH_COMPANIES_SUCCESS = "FETCH_COMPANIES_SUCCESS";
export const FETCH_COMPANIES_FAIL = "FETCH_COMPANIES_FAIL";

export const FETCH_COMPANY_BY_ID_START = "FETCH_COMPANY_BY_ID_START";
export const FETCH_COMPANY_BY_ID_SUCCESS = "FETCH_COMPANY_BY_ID_SUCCESS";
export const FETCH_COMPANY_BY_ID_FAIL = "FETCH_COMPANY_BY_ID_FAIL";

// export const ADD_COMPANY_START = "ADD_COMPANY_START";
// export const ADD_COMPANY_SUCCESS = "ADD_COMPANY_SUCCESS";
// export const ADD_COMPANY_FAIL = "ADD_COMPANY_FAIL";

// export const EDIT_COMPANY = "EDIT_COMPANY";

export const DELETE_COMPANY_BY_ID_START = "DELETE_COMPANY_BY_ID_START";
export const DELETE_COMPANY_BY_ID_SUCCESS = "DELETE_COMPANY_BY_ID_SUCCESS";
export const DELETE_COMPANY_BY_ID_FAIL = "DELETE_COMPANY_BY_ID_FAIL";
